# Site settings
title: The Prism Alignment Project
email: hannah@thekirks.co.uk
formid: xqkvjyvw
url: "https://hannahkirk.github.io/prism-alignment"
description: "Welcome to the Prism Alignment Project."
keywords: "It's time more people contributed to LLM development."
skills: "Participatory - Representative - Individualised - Subjective - Multicultural"
meta_author: Hannah Rose Kirk

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# # If you use disqus you need disqus shortname
# # https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  logo: fdfae9
  primary: ff8a67 #102f41
  primary-rgb: "118,141,153"
  pale: ebe2cd
  secondary: 223034 #FD6E8A
  secondary-dark: 223034 #A2122F
  red: ff8a67
  yellow: ffc24c
  green: b7e5ca
  teal: 80e2d8
  blue: 32bcdd

# Footer settings
footer:
  copyright: Hannah Rose Kirk
  location: We're still building...
  social: Find Us Elsewhere
  credits: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/hannahrosekirk
  - title: github
    url: https://github.com/HannahKirk/prism-alignment/

# Postal address (add as many lines as necessary)
address:
  - line: ...Check back soon for updates!

# Credits content
credits: 'Theme thankfully borrowed from <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
